apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
- resources:
  - '*.*'
  providers:
  - kms:
      apiVersion: v2
      name: kms-health-kind-fake
      endpoint: unix:///var/run/kmsplugin-fake/kms.sock
  - identity: {}
