apiVersion: v1
kind: Pod
metadata:
  name: {{.InstallerPodName}}
  namespace: {{.Namespace}}
  labels:
    app: openshift-kms-preflight-installer
spec:
  automountServiceAccountToken: false
  nodeSelector:
    node-role.kubernetes.io/master: ""
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoExecute"
  initContainers:
    - name: cleanup
      image: {{.InstallerImage}}
      imagePullPolicy: IfNotPresent
      terminationMessagePolicy: FallbackToLogsOnError
      command:
        - /bin/sh
        - -c
        - |
          #!/bin/sh
          set -euo pipefail

          rm -f {{.PodManifestDir}}/{{.PodManifestFile}}
          rm -rf {{.ResourceDir}}/secrets/{{.SecretDirName}}
      securityContext:
        privileged: true
        runAsUser: 0
      resources:
        requests:
          memory: 10Mi
          cpu: 10m
      volumeMounts:
        - mountPath: {{.PodManifestDir}}
          name: manifests-dir
        - mountPath: {{.ResourceDir}}
          name: resource-dir
  containers:
    - name: installer
      image: {{.InstallerImage}}
      imagePullPolicy: IfNotPresent
      terminationMessagePolicy: FallbackToLogsOnError
      command:
        - /bin/sh
        - -c
        - |
          #!/bin/sh
          set -euo pipefail

          target_secret_dir="{{.ResourceDir}}/secrets/{{.SecretDirName}}"
          mkdir -p "${target_secret_dir}"
          cp -f /install/secret/* "${target_secret_dir}/"

          manifest_path="{{.PodManifestDir}}/{{.PodManifestFile}}"
          mkdir -p {{.PodManifestDir}}
          cp -f /install/pod/pod.yaml "${manifest_path}"
          chmod 0600 "${manifest_path}"
      securityContext:
        privileged: true
        runAsUser: 0
      resources:
        requests:
          memory: 10Mi
          cpu: 10m
      volumeMounts:
        - mountPath: {{.PodManifestDir}}
          name: manifests-dir
        - mountPath: {{.ResourceDir}}
          name: resource-dir
        - mountPath: /install/pod
          name: pod-manifest
        - mountPath: /install/secret
          name: encryption-config
          readOnly: true
  restartPolicy: Never
  priorityClassName: system-node-critical
  securityContext:
    runAsUser: 0
  volumes:
    - hostPath:
        path: {{.PodManifestDir}}
      name: manifests-dir
    - hostPath:
        path: {{.ResourceDir}}
      name: resource-dir
