apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .TargetNamespace }}
  name: guard-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["list"]